name: CI/CD Pipeline for Inventory Management System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Linting (flake8)
    - name: Run Linting
      run: |
        pip install flake8
        flake8 .

    # Step 5: Run Tests (pytest)
    - name: Run Tests
      run: |
        pip install pytest
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Deploy (Placeholder)
    - name: Deploy application
      run: |
        echo "Deployment script here, e.g., SCP or Heroku deploy"
